2020-10-05 22:21:36,996 ERROR: Exception on / [GET] [in C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\routes.py", line 33, in index
    posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\templates\base.html", line 50, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\templates\_post.html", line 14, in top-level template code
    {{ _('%(username)s said %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\jinja2\ext.py", line 140, in gettext
    rv = __context.call(func, __string)
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_babel\__init__.py", line 109, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_babel\__init__.py", line 209, in get_translations
    return get_domain().get_translations()
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_babel\__init__.py", line 554, in get_translations
    locale = get_locale()
  File "C:\Users\Marta\Anaconda3\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py", line 67, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAEGS'])
KeyError: 'LANGUAEGS'
2020-10-05 22:22:43,211 INFO: Microblog startup [in C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py:62]
2020-10-05 22:48:13,338 INFO: Microblog startup [in C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py:62]
2020-10-05 22:49:35,212 INFO: Microblog startup [in C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py:62]
2020-10-05 23:07:55,575 INFO: Microblog startup [in C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py:62]
2020-10-05 23:13:50,141 INFO: Microblog startup [in C:\Users\Marta\PycharmProjects\Pyth-Course-FlaskMicroblog\app\__init__.py:62]
